name: Setup Sample Data on Deploy

on:
  push:
    branches:
      - deploy

jobs:
  setup-db:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Remove existing DB
        run: npx ts-node remove_db.ts

      - name: Insert sample data
        run: npx ts-node insert_sample_data.ts
